sudo: required
services:
    - docker

before_install:
    - docker build -t cowboysr0ck9/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true cowboysr0ck9/react-test npm test

after_success:
    # Builds Docker Images
    - docker build -t cowboysr0ck9/multi-client ./client
    - docker build -t cowboysr0ck9/multi-nginx ./nginx
    - docker build -t cowboysr0ck9/multi-server ./server
    - docker build -t cowboysr0ck9/multi-worker ./worker

    # Login to Docker HUB CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Push Images to Docker Hub
    - docker push cowboysr0ck9/multi-client
    - docker push cowboysr0ck9/multi-nginx
    - docker push cowboysr0ck9/multi-server
    - docker push cowboysr0ck9/multi-worker

    deploy:
        edge: true
        provider: elasticbeanstalk
        region: us-east-1
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-east-1-432271918838
        bucket_path: multi-docker
        on:
            branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
            secure: $AWS_SECRET_KEY