sudo: required
services:
    - docker

before_install:
    - docker build -t eadsgraphic/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true eadsgraphic/react-test npm test

after_success:
    # Builds Docker Images
    - docker build -t eadsgraphic/multi-client ./client .
    - docker build -t eadsgraphic/multi-nginx ./nginx .
    - docker build -t eadsgraphic/multi-server ./server .
    - docker build -t eadsgraphic/multi-worker ./worker .

    # Login to Docker HUB CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Push Images to Docker Hub
    - docker push eadsgraphic/multi-client
    - docker push eadsgraphic/multi-nginx
    - docker push eadsgraphic/multi-server
    - docker push eadsgraphic/multi-worker
